version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9-rc-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: start selenium GRID
          command: |
            echo "CHROME VERSION"
            google-chrome --version || echo $
            TEST_IP_ADDRESS=`hostname --ip-address`
            echo "export TEST_IP_ADDRESS=$TEST_IP_ADDRESS" >> $BASH_ENV
            echo "IP ADDRESS: $TEST_IP_ADDRESS"
            chmod +x tools/chromedriver
            chmod +x tools/selenium-server-standalone-3.141.59.jar
            mkdir grid-logs
            chmod -R 755 grid-logs
            java -jar tools/selenium-server-standalone-3.141.59.jar -role hub
          no_output_timeout: 1m
          background: true

      - run:
          name: start node GRID
          command: |
            java -jar tools/selenium-server-standalone-3.141.59.jar -role node
          no_output_timeout: 1m
          background: true

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run ui_smoke tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m smoke -v
      - run:
          name: run ui_regression tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m regression -v

      - store_artifacts:
          path: grid-logs
          destination: grid-logs
          when: always