version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9-rc-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: start selenium GRID
          command: |
            java -version
            chmod +x tools/chromedriver
            chmod +x tools/selenium-server-standalone-3.141.59.jar
            mkdir grid-logs
            chmod -R 755 grid-logs
            java -jar tools/selenium-server-standalone-3.141.59.jar -role hub -log hub.log &
            sleep 10
      - run:
          name: start node GRID
          command: |
            java -jar tools/selenium-server-standalone-3.141.59.jar -role node -log node.log &

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run ui_smoke tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m smoke -v
      - run:
          name: run ui_regression tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m regression -v
